### ISSUE TITLE
Would you consider to use a web framework for the general functionalities?

### ISSUE THREAD

**Issue by NalaGinrut** [jjba23/byggsteg#3]
Hi @jjba23 !
I just happened to pass and I saw this cool project. 

I found that you've managed to write many code for server, route, log, and json, static files. And these code could be handled by a web framework. So that you may focus on the core functionalities, and save the energy to maintain general things.

So I'm here to shamelessly "sell" GNU Artanis which is a modern web framework written in GNU Guile as well. ;-P
If you're interested in throwing the general parts to GNU Artanis, I can help.
Here it is https://artanis.dev

**Comment by jjba23** [comment]
Good evening @NalaGinrut thanks a lot for your interest in byggsteg and my code 😺 

I have fallen in love with Artanis, and its elegance ❤️  as well as that bangin' website!

Any PR will be welcome to byggsteg, after review, thanks for sharing and the proposal. 💚 
I will also love to learn more and start using Artanis in more of my Scheme projects!

**Comment by NalaGinrut** [comment]
I'll fork and make the initial work. Later I'll write a MVC tutorial on Artanis blog.
I have limited time so we may in a a slower pace.

**Comment by jjba23** [comment]
As discussed, we continue in Codeberg! :)
